# Generated by Django 4.2.3 on 2023-08-02 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_application', to='products.contract'),
        ),
        migrations.AlterField(
            model_name='product',
            name='credit_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.creditapplication'),
        ),
    ]
